### PR TITLE
logic for edmc prompt and handle in mission creation

### PR DESCRIPTION
**Pull request by skiedude**
https://user-images.githubusercontent.com/6210395/197092808-be8bc043-0733-4524-b35c-24ec1cb03311.mp4

1. New prompt with `y/n` for EDMC Off mission type
2. Send text message + 2 images
3. Inform edmc message was sent

### CODE REVIEW

**Comment by cimspin** [comment]
Looking great, our CCOs will love having this functionality finally automated. I had hoped to find a more elegant way than another y/n prompt to do it but we can sort that out when the bot switches entirely to discord.py 2.0 and moves to interaction-based commands

**Comment by TuggyBoat** [comment]
> Looking great, our CCOs will love having this functionality finally automated. I had hoped to find a more elegant way than another y/n prompt to do it but we can sort that out when the bot switches entirely to discord.py 2.0 and moves to interaction-based commands

Would it be simpler if instead of asking for a `y/n`, we just include another character in `  embed = discord.Embed(title="Where would you like to send the alert?",
                            description="(**d**)iscord, (**r**)eddit, (**t**)ext for copy/pasting or (**x**) to cancel\n"
                            "Use (**n**) to also notify PTN Haulers.",`?

**Comment by skiedude** [comment]
> > Looking great, our CCOs will love having this functionality finally automated. I had hoped to find a more elegant way than another y/n prompt to do it but we can sort that out when the bot switches entirely to discord.py 2.0 and moves to interaction-based commands
> 
> Would it be simpler if instead of asking for a `y/n`, we just include another character in ` embed = discord.Embed(title="Where would you like to send the alert?", description="(**d**)iscord, (**r**)eddit, (**t**)ext for copy/pasting or (**x**) to cancel\n" "Use (**n**) to also notify PTN Haulers.",`?

Thats not a bad idea, I just wonder how if its easier to go unnoticed forgotten there, vs its own prompt you have to pass (for now)

**Comment by skiedude** [comment]
> Looking great, our CCOs will love having this functionality finally automated. I had hoped to find a more elegant way than another y/n prompt to do it but we can sort that out when the bot switches entirely to discord.py 2.0 and moves to interaction-based commands

Yeah until we have access to Modals, its mostly just up to a prompt of some sorts. We could potentially just key off the profit listed?

I know there is code that if is < 10 then it doesn't post it, what if we added a check that if its > 30 then we auto enable edmc messages? @cimspin

**Comment by TuggyBoat** [comment]
> Yeah until we have access to Modals, its mostly just up to a prompt of some sorts. We could potentially just key off the profit listed?
> 
> I know there is code that if profit is < 10 then it doesn't post it, what if we added a check that if profit is > 30 or 25? then we auto enable edmc messages? @cimspin

CG's would bung this up with the greater profit values.

**Comment by cimspin** [comment]
> > > Looking great, our CCOs will love having this functionality finally automated. I had hoped to find a more elegant way than another y/n prompt to do it but we can sort that out when the bot switches entirely to discord.py 2.0 and moves to interaction-based commands
> > 
> > 
> > Would it be simpler if instead of asking for a `y/n`, we just include another character in ` embed = discord.Embed(title="Where would you like to send the alert?", description="(**d**)iscord, (**r**)eddit, (**t**)ext for copy/pasting or (**x**) to cancel\n" "Use (**n**) to also notify PTN Haulers.",`?
> 
> Thats not a bad idea, I just wonder how if its easier to go unnoticed forgotten there, vs its own prompt you have to pass (for now)

Let's go with this solution. Add `Use (**e**) to flag the mission as EDMC-OFF.` to that embed. CCOs are always notified of new changes and (as you can see lol) most new options have indeed gone into this dialogue.

> Yeah until we have access to Modals, its mostly just up to a prompt of some sorts. We could potentially just key off the profit listed?
> 
> I know there is code that if profit is < 10 then it doesn't post it, what if we added a check that if profit is > 30 or 25? then we auto enable edmc messages? @cimspin

Let's keep in as a manual opt-in as we do sometimes post high margin trades to reddit and don't want CCOs prevented from doing so. The reason low margin trades are disallowed is because it breaks our 10k/ton rule but is necessary for booze cruise loading.

However, what would be good that I forgot to mention earlier is to automatically skip reddit posting if EDMC-off is flagged, _even if the CCO selects it_. (A lot of the time it's just muscle memory and people goof up.) Just return a "Skipped posting to Reddit as you requested EDMC-OFF" message similar to the current wine loading Reddit skip message (line 1350 in your commit, 1329 in original) and then move on

**Comment by cimspin** [comment]
Just because no good deed goes unpunished, can we pin the EDMC off message too?

**Comment by cimspin** [comment]
To add, from discussions on Discord:
- "t" should not generate a mission in the database (but "d" and "r" still do)
- carrier channel should only be created if "d" is chosen
- "n" should only work if "d" is chosen, and return a graceful "no" if used without "d"

**Comment by skiedude** [comment]
> To add, from discussions on Discord:
> 
> * "t" should not generate a mission in the database (but "d" and "r" still should)
> * carrier channel should only be created if "d" is chosen
> * "n" and "e" should only work if "d" is chosen, and return a graceful "no" if used without "d"

Logic has been updated, tested multiple use cases that I could think of on the test discord

**Comment by chandru9279** [comment]
How about this gif also?

EDMC_OFF

**Review by cimspin — APPROVED** [review]
My brain is mince this morning but trusting in your testing and putting this through :)

**Comment by skiedude** [comment]
1. updated the edmc message to be an embed with new description/title
2. embed random edmc_off_* image in the edmc embed
3. create default timeout warning function
4. variablized the string that we check against in the check_confirm function for gen_missions

edmc1
edmc2

**Review by cimspin — APPROVED** [review]
Awesome sauce

**Pull request merged**
