### PR TITLE
349 - Show ;stock <carrier> in discord embed under 'm.complete will mark this mission complete'

### PR DESCRIPTION
**Pull request by Conshmea**

### CODE REVIEW

**Comment by durzo** [comment]
I don't like this because stock levels are not accurate and can be delayed by hours, days or even weeks due to EDSM. best case cAPI is 1 hour behind real data.

**Comment by Conshmea** [comment]
> 

Really?

**Comment by durzo** [comment]
carriers are added to each bot separately and are not guaranteed to match. we could pass the carrier registration ID instead, but this feature is not yet in stockbot prod (still in test server)

**Comment by Conshmea** [comment]
Yeah that does cause a bit of a problem

**Comment by durzo** [comment]
even with carrier ID's. there is no guarantee the carrier will even exist in stockbot

**Comment by gcruicks** [comment]
Please use the issue as the title, Update XYZ is not descriptive of what is changing.

**Comment by gcruicks** [comment]
> If it is different between the 2 someone could change it, and after a while all the in-use carriers will be synced. Not a perfect solution though

Yes, but that is out of the scope of this PR. and would be better handled by linking the bots together somehow.

**Review by cimspin — APPROVED** [review]
Deployable now that shortnames have been synchronized manually with stockbot

**Pull request merged**
