### PR TITLE
eng/PR-10 Refactor into a streamlined structure

### PR DESCRIPTION
**Pull request by gcruicks**
Refactored to a slightly more streamlined structure, removed all globals.
Added new classes for carrier data, mission data and commodity informations.
Cleaned up method names and some method logics.

Fixes: #10

### CODE REVIEW

**Comment by gcruicks** [comment]
Finished testing this, seems to be working as intended now. Appreciate some more testing though!

**Comment by cimspin** [comment]
findcomm needs a message for when it finds nothing, that's as far as I got when testing this time!

**Comment by cimspin** [comment]
Only a couple of things I noted:
- 6026173885a01048ccd1df17da79f08d2aa2044c doesn't seem to return the expected error when searching for an invalid commodity
- carrier_del returns an error even if successful: `    await ctx.send(f"Couldn't find a carrier with ID #{db_id}.")` (line 1019)

Was unable to test Reddit functions owing to issue #54 - missing a duplicate upvotes channel on test server (and appropriate conf in code). See also #55 - failing to send to missing upvotes channel causes mission not to be generated.

**Comment by gcruicks** [comment]
> Only a couple of things I noted:
> 
> * [6026173](https://github.com/PilotsTradeNetwork/MissionAlertBot/commit/6026173885a01048ccd1df17da79f08d2aa2044c) doesn't seem to return the expected error when searching for an invalid commodity
> * carrier_del returns an error even if successful: `    await ctx.send(f"Couldn't find a carrier with ID #{db_id}.")` (line 1019)
> 
> Was unable to test Reddit functions owing to issue #54 - missing a duplicate upvotes channel on test server (and appropriate conf in code). See also #55 - failing to send to missing upvotes channel causes mission not to be generated.

Fixed the find commodity call by implementing the Boolean logic on Commodity.
Fixed the carrier_del

**Review by cimspin — APPROVED** [review]

**Pull request merged**
