### PR TITLE
Check for orphaned trade channels that lost their timer

### PR DESCRIPTION
**Pull request by skiedude**
Lots of pretty reds and greens!

### Cleanup
**Database Config**
1. The table create strings were repeated in multiple places, now have one global string to rule them all
2. Define the list of columns for easier reference in functions

**Create functions for table and column checking**
1. Use a dict to define the tables and _new_ columns that should exist
2. Loop through each entry and pass to the function that checks the specific data type

### Prune orphaned trade channels on bot.on_ready
1. Create new table `channel_cleanup` in the missions database with `channelid|is_complete`
2. On mission creation set `is_complete = 0`
3. On mission complete/done mark `is_complete=1`
4. On successful channel deletion, remove entry from channel_cleanup table
5. Create a new task to run the query against the new table `channel_cleanup`
6. If any entries exist with `is_complete = 1`, send them to remove channel

### CODE REVIEW

**Comment by cimspin** [comment]
Phew! Might take me a while to get to the point of being able to review this. @gcruicks feel free to take a look if you're able. @skiedude presume you have thoroughly tested and all normal mission commands are working (`/info`, `/mission`, `/missions` as well as m.load/unload, m.complete, m.done etc)?

**Comment by skiedude** [comment]
> Phew! Might take me a while to get to the point of being able to review this. @gcruicks feel free to take a look if you're able. @skiedude presume you have thoroughly tested and all normal mission commands are working (`/info`, `/mission`, `/missions` as well as m.load/unload, m.complete, m.done etc)?

I have done testing, I will do another round to be 100% sure. The actual code changes to the mission commands is super minimal, just updating a new table that exists. 

The big scary red/greens are mostly the consolidation of all the table/column checks that were copy pastes now put into 2 functions.

**Comment by skiedude** [comment]
Branch updated with latest changes from the edmc changes that were just merged

**Comment by skiedude** [comment]
Testing:

Create 3 separate trade missions:
`#nac-matterhorn`
`#ptn-skiedude`
`#ptn-everest`

Complete all 3 (1 with m.done the others with m.complete)

Stop the bot before the timers run out

Startup the bot, and observe bot output discovering the 3 channels that have `is_complete = 1`
```
MissionAlertBot (Test) has connected to Discord!
Checking for trade channels that were not cleaned up before bot restart
Sending channel 1034968971679641730 for removal
Starting 60 second countdown for deletion of ptn-everest
Sending channel 1034970650332381264 for removal
Starting 60 second countdown for deletion of nac-matterhorn
Sending channel 1034970715914518548 for removal
Starting 60 second countdown for deletion of ptn-skiedude
last trade cron running.
All carriers have been processed.
```

Before the timer reaches 60 seconds, start another mission for `#nac-matterhorn` 

60 second timer is up for all 3 tasks (would be 15 min in prod)
```
Channel removal timer complete
Channel removal timer complete
Channel removal timer complete
Attempting channel lock...
Channel lock acquired.
Attempting channel lock...
Attempting channel lock...
```

I believe we have already increased the channel lock timeout (if not that should be done) as we will have multiple channels attempt to delete at the same time and obtain the same single lock

First channel is deleted and the next channel obtains the lock
```
Deleted ptn-everest
Channel lock released
Channel lock acquired.
```

Next channel is the one with a new mission started
```
Mission data from remove_carrier_channel: MissionData: CarrierName:N.A.C MATTERHORN....
New mission underway in this channel, aborting removal
Channel lock released
Channel lock acquired.
Mission data from remove_carrier_channel: MissionData: CarrierName:None....
Deleted ptn-skiedude
Channel lock released
```

Successfully skips the new mission in progress even though we had a task queued to delete it. Continues to delete the next channel

**Review by cimspin — APPROVED** [review]

**Pull request merged**
