### PR TITLE
/carrier_edit, checking correct channel, no nominating

### PR DESCRIPTION
**Pull request by skiedude**
1. #267 Do not allow nominating anyone in Council, Mod, CMentor, Cpillar (4297-4306)
2. Remove references to the db_sql folder (`create_missing_table` and `dump_database_test`)
3. Add a decorator to replace the `current_channel != desired_channel` for easier use
4. #143 Instead of asking the user which carrier fields they wish to edit, turn this into a slash command that uses views/modals for simple field editing. 
5. Related to 4, remove methods that are no longer in use that were transformed into the new views/modals

See discord for video/picture demo https://discord.com/channels/800080948716503040/827656814911815702/1053903633655287848

### CODE REVIEW

**Comment by cimspin** [comment]
This is great but point 2 should probably be reverted as the db_sql change was my incompetence, not intended.

**Comment by skiedude** [comment]
> This is great but point 2 should probably be reverted as the db_sql change was my incompetence, not intended.

Should db_sql still be in the .gitignore as well? I can bring the functions back, but if its in the .gitignore and you don't have a local copy it fails with an error. I can code around that as well, but wondering what all needs to come back besides just those functions

**Comment by cimspin** [comment]
> > This is great but point 2 should probably be reverted as the db_sql change was my incompetence, not intended.
> 
> Should db_sql still be in the .gitignore as well? I can bring the functions back, but if its in the .gitignore and you don't have a local copy it fails with an error. I can code around that as well, but wondering what all needs to come back besides just those functions

The directory should probably exist, but the SQL files should be ignored? I ... don't know. I think the purpose was to have backups of the databases but I'm not sure how they're supposed to be managed with regard to git.

**Comment by skiedude** [comment]
> > > This is great but point 2 should probably be reverted as the db_sql change was my incompetence, not intended.
> > 
> > 
> > Should db_sql still be in the .gitignore as well? I can bring the functions back, but if its in the .gitignore and you don't have a local copy it fails with an error. I can code around that as well, but wondering what all needs to come back besides just those functions
> 
> The directory should probably exist, but the SQL files should be ignored? I ... don't know. I think the purpose was to have backups of the databases but I'm not sure how they're supposed to be managed with regard to git.

From what I can discern the sql files in db_sql are **table** backups on top of the whole database backup we run anytime a change is made to the database. 
I'll see if I can find a happy medium in my next commit

**Comment by skiedude** [comment]
Brought back those 2 methods, and added a check to create the `db_sql` in the backup_test. The create_missing table has a check in place to only us it if that dir exists.

**Review by cimspin — APPROVED** [review]
Thank you for fixing my mistakes too :D

**Review by cimspin — APPROVED** [review]

**Pull request merged**
